import {StyleSheet, Dimensions} from "react-native";

const {width} = Dimensions.get("window");
const height = width * 0.4;

export const styles = StyleSheet.create({
  allPage: {
    backgroundColor: "#F0F0F0",
    // backgroundColor: "#436B92",
  },
  header: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    height: height * 1.2,
  },
  loginLogo: {
    width: "43%",
    height: "32%",
    marginLeft: "25%",
    top: 15,
    left: 5,
  },
  body: {
    bottom: "10%",
  },
  hairline: {
    backgroundColor: "#ff9e1f",
    height: 2,
    width: 90,
  },

  comparePriceBanner: {
    flexDirection: "row",
    alignItems: "center",
    top: "4%",
    left: "6%",
  },

  loginButtonBelowTextBorder: {
    paddingHorizontal: 35,
    color: "#FFF",
    borderWidth: 4,
    backgroundColor: "#ff7c00",
    borderColor: "#ff7c00",
    borderRadius: 25,
  },
  loginButtonBelowText: {
    fontSize: 14,
    color: "#FFF",
  },
  scroll: {
    width,
    height: height * 1,
    bottom: "56%",
  },
  imageCarousel: {
    width: width * 0.9,
    left: 18,
    height: height * 0.65,
    marginTop: 30,
    marginRight: 40,
    borderColor: "#436B92",
    borderWidth: 1,
    borderRadius: 20,
    resizeMode: "cover",
  },
  imageBannerPartner: {
    bottom: 30,
    width: width * 0.9,
    left: 18,
    height: height * 0.5,
    marginTop: 10,
    marginRight: 40,
    borderRadius: 10,
    shadowColor: "black",
    shadowOffset: {
      width: width * 0.003,
      height: height * 0.002,
    },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  pagination: {
    flexDirection: "row",
    position: "absolute",
    bottom: height * 1.05,
    alignSelf: "center",
  },
  pagingText: {
    // fontSize: width / 70,
    margin: 3,
    borderRadius: 100,
    borderWidth: 3,
    borderColor: "grey",
    bottom: 50,
    width: 7,
    height: 7,
  },
  pagingActiveText: {
    margin: 3,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#fff",
    backgroundColor: "#fff",
    width: 15,
    bottom: 50,
  },
  opacity: {
    backgroundColor: "#fff",
    shadowOffset: {
      width: 0,
      height: 12,
    },
    borderRadius: 30,
    borderColor: "grey",
    shadowOpacity: 10,
    shadowRadius: 10.0,
    shadowColor: "black",
    elevation: 20,
    top: "7%",
    left: "4%",
    width: "90%",
  },
  putAdButton: {
    textAlign: "center",
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "#324160",
    color: "#fff",
    backgroundColor: "#324160",
    marginTop: 10,
    marginBottom: 10,
  },
  searchBarContainer: {
    backgroundColor: "#F0F0F0",
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    borderColor: "#F0F0F0",
    borderWidth: 1,
    bottom: height * 0.9,
    width: width * 0.9,
    height: height * 0.35,
  },
  inputSearchBar: {
    flex: 1,
    fontSize: 16,
    padding: 10,
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 20,
    color: "#436B92",
  },
  seeMoreContainer: {
    flexDirection: "row",
    left: "5%",
  },
  seeMoreButton: {paddingVertical: 4, marginLeft: "3%"},
  seeMoreText: {
    color: "#ff7b0d",
    fontSize: 16,
    fontWeight: "500",
  },
  imageProduct: {
    width: "95%",
    height: height * 0.9,
    left: 10,
  },
  banneerPartner: {
    bottom: height * 2.6,
  },
  halfCircle: {
    borderRadius: 50,
    borderColor: "#f0f0f0",
    borderWidth: 1,
    width: width * 1.02,
    right: 3,
    height: height * 0.8,
    bottom: height * 2,
    backgroundColor: "#F0F0F0",
  },
  kelklopeLogo: {
    width: width * 0.5,
    height: height * 0.2,
    bottom: height * 1,
  },
  backgroundHeader: {
    width: width * 1,
    height: height * 1.3,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: "#436B92",
    backgroundColor: "#436B92",
  },
  backgroundHeader2: {
    width: width * 1,
    height: height * 1.5,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: "#436B92",
    backgroundColor: "#436B92",
  },
  eachElement: {
    bottom: height * 2.8,
  },
  image: {
    width: 200,
    height: 200,
  },
  carousselContainer: {
    shadowColor: "black",
    shadowOffset: {
      width: width * 0.003,
      height: height * 0.002,
    },
    shadowOpacity: 0.6,
    shadowRadius: 5,
  },
});
