import {Dimensions, StyleSheet} from "react-native";

const {height, width} = Dimensions.get("window");

export const styles = StyleSheet.create({
  directionRow: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: "100%",
    marginHorizontal: 10,
  },
  header: {
    height: height * 0.2,
    width: width * 1,
    backgroundColor: "#436B92",
    borderColor: "#436B92",
    borderWidth: 1,
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.5,
    shadowRadius: 5,
  },
  myAccountText: {
    fontFamily: "ManropeBold",
    color: "#fff",
    fontSize: 28,
    left: width * 0.04,
  },
  optionsConnectionButton: {
    left: width * 0.037,
  },
  inscriptionButton: {
    width: width * 0.92,
    height: height * 0.055,
    left: width * 0.036,
    color: "#436B92",
    borderWidth: 1,
    backgroundColor: "#436B92",
    borderColor: "#436B92",
    borderRadius: 8,
  },
  inscriptionText: {
    textAlign: "center",
    paddingVertical: height * 0.014,
    color: "#FFF",
    fontFamily: "ManropeSemiBold",
    fontSize: 17,
  },
  middleLine: {
    borderRadius: 1,
    borderWidth: 0.5,
    borderColor: "#262626",
    width: width * 0.8,
    left: width * 0.08,
    top: height * 0.025,
  },
  underLineButton: {
    marginTop: 15,
    width: width * 0.92,
    height: 50,
    borderWidth: 1,
    backgroundColor: "#fff",
    borderColor: "#6666",
    borderRadius: 8,
  },
  underLineText: {
    color: "#262626",
    fontFamily: "ManropeRegular",
    fontSize: 17,
  },
  allBlock: {},
  bottomText: {
    fontFamily: "ManropeRegular",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 45,
  },
  modalView: {
    margin: 10,
    backgroundColor: "#F0F0F0",
    width: width * 1,
    height: height * 0.94,
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 2,
  },
  abordTouchable: {
    right: width * 0.38,
    top: height * 0.004,
  },
  abortText: {
    color: "#436B92",
    fontFamily: "ManropeRegular",
    fontSize: 16,
  },
  setPersonalInformations: {
    width: width * 0.92,
    height: height * 0.055,
    borderWidth: 1,
    backgroundColor: "#fff",
    borderColor: "#6666",
    borderRadius: 8,
    left: width * 0.03,
    top: height * 0.115,
  },
  setPersonalInformationsText: {
    color: "#262626",
    fontFamily: "ManropeRegular",
    fontSize: 17,
    paddingVertical: height * 0.014,
    left: width * 0.12,
  },
  accountManagement: {left: width * 0.03, top: height * 0.01},
  confidentialityButton: {},
  legalMentions: {},
  arrowIcon: {},
  AccountMainMenuContainer: {
    alignItems: "center",
    height: "50%",
    justifyContent: "space-between",
    marginTop: 10,
  },
  bottomContainer: {
    justifyContent: "space-around",
    alignItems: "center",
    height: height * 0.1,
  },
});
