import {StyleSheet, Dimensions} from "react-native";

const {width} = Dimensions.get("window");
const height = width * 0.4;

export const styles = StyleSheet.create({
  cptOfferView: {
    borderRadius: 20,
    borderColor: "#436B92",
    backgroundColor: "#436B92",
    borderWidth: 1,
    width: width * 0.3,
    textAlign: "center",
    right: width * 0.05,
    bottom: height * 0.1,
  },
  cptOfferText: {
    fontSize: 20,
    color: "#fff",
    textAlign: "center",
    fontFamily: "ManropeSemiBold",
  },
  bestPriceTextView: {
    borderBottomRightRadius: 7,
    borderTopLeftRadius: 15,
    borderColor: "#ff8D26",
    borderWidth: 1,
    width: width * 0.3,
    height: height * 0.15,
    backgroundColor: "#ff8D26",
    bottom: height * 0.009,
    right: width * 0.005,
    marginBottom: -15,
  },
  offerPrice: {
    fontSize: 30,
    paddingLeft: 17,
    fontFamily: "ManropeBold",
  },
  tva: {
    paddingLeft: 17,
    color: "grey",
    fontSize: 13,
    fontFamily: "ManropeRegular",
  },
  validity: {
    color: "#666666",
    paddingLeft: 17,
    fontSize: 9,
    bottom: height * 0.21,
    width: width * 0.4,
    fontFamily: "ManropeRegular",
  },
  allOffer: {
    flexDirection: "column",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#fff",
    borderRadius: 10,
    left: width * 0.02,
    width: width * 0.92,
    height: height * 0.7,
    marginBottom: -5,
  },
  checkOfferText: {
    color: "#ff7c00",
    fontSize: 18,
    textAlign: "center",
    fontFamily: "ManropeSemiBold",
  },
  redirectionToOfferSite: {
    left: width * 0.6,
    borderRadius: 8,
    borderColor: "#ff7c00",
    borderWidth: 1.5,
    bottom: height * 0.25,
    width: width * 0.3,
    height: height * 0.22,
    paddingVertical: height * 0.025,
  },
  eachOffer: {
    marginBottom: -10,
    shadowColor: "black",
    shadowOffset: {
      width: width * 0.003,
      height: height * 0.002,
    },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    zIndex: 1,
  },
  firstOffer: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#fff",
    borderRadius: 10,
    left: width * 0.02,
    top: height * 0.05,
    width: width * 0.92,
    height: height * 0.75,
  },
  shopLogo: {
    width: 100,
    height: 100,
    bottom: height * 0.5,
    left: width * 0.6,
  },
  avalaible: {
    color: "#666666",
    paddingLeft: 17,
    fontSize: 9,
    bottom: height * 0.5,
    width: width * 0.4,
    fontFamily: "ManropeRegular",
  },
  imageShopContainer: {
    height: height * 0.35,
    width: width * 0.25,
  },
  bestPriceText: {
    color: "#fff",
    textAlign: "center",
    fontFamily: "ManropeRegular",
  },
  logoShop: {
    width: "100%",
    height: "100%",
    bottom: height * 0.3,
    left: width * 0.6,
  },
});
