import {Dimensions, StyleSheet, Platform} from "react-native";

const {width, height} = Dimensions.get("window");

export const styles = StyleSheet.create({
  OtherModules: {bottom: height * 0.2},
  MainContainer: {
    flex: 1,
    paddingTop: Platform.OS === "ios" ? 20 : 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    top: height * 0.35,
  },
  discoverButton: {
    color: "#fff",
    borderRadius: 25,
    borderColor: "#ff8D26",
    borderWidth: 1,
    backgroundColor: "#ff8D26",
    width: width * 0.5,
    height: height * 0.065,
    top: height * 0.1,
    left: width * 0.3,
    zIndex: 3,
  },
  discoverText: {
    color: "#fff",
    height: height * 0.06,
    textAlign: "center",
    paddingVertical: height * 0.01,
    fontSize: 25,
    fontWeight: "bold",
    fontFamily: "ManropeBold",
  },
  orangeCircleView: {
    width: width * 0.75,
    height: height * 0.65,
    borderRadius: 150,
    backgroundColor: "#ff8D26",
    zIndex: 5,
  },
  kelklopeLogo: {
    width: width * 0.46,
    height: height * 0.05,
    bottom: height * 1.4,
    zIndex: 7,
  },
  einsteinImage: {
    height: height * 0.35,
    width: width * 0.55,
    bottom: height * 1.35,
    zIndex: 7,
  },
  leftArrow: {
    height: height * 0.15,
    width: width * 0.3,
    bottom: height * 1.14,
    right: width * 0.2,
    zIndex: 6,
  },
  rightArrow: {
    height: height * 0.15,
    width: width * 0.3,
    bottom: height * 1.57,
    left: width * 0.18,
    zIndex: 6,
  },
  secondPartView: {
    display: "flex",
    flexDirection: "column",
    bottom: height * 2.15,
    width: "80%",
    right: 5,
    zIndex: 3,
  },
  slogan: {
    fontSize: 30,
    color: "#fff",
    fontWeight: "bold",
    fontFamily: "ManropeBold",
    zIndex: 3,
  },
  presentationText: {
    fontSize: 17,
    color: "#fff",
    marginTop: 30,
    fontFamily: "ManropeRegular",
    zIndex: 3,
  },
  whiteCircleView: {
    top: height * 0.65,
    width: width * 0.75,
    height: height * 0.9,
    borderRadius: 150,
    backgroundColor: "#fff",
    zIndex: 3,
  },
  blueCircleView: {
    width: width * 0.75,
    height: height * 1,
    borderRadius: 20,
    bottom: height * 0.2,
    backgroundColor: "#436B92",
    zIndex: 2,
  },
});
