import {StyleSheet, Dimensions} from "react-native";

const {width, height} = Dimensions.get("window");

export const styles = StyleSheet.create({
  row: {
    flexDirection: "row",
    flex: 1,
    alignItems: "center",
    paddingLeft: 5,
    backgroundColor: "#efefef",
    margin: 20,
    minHeight: 50,
  },

  item: {
    backgroundColor: "#fff",
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  rightActions: {
    backgroundColor: "red",
    flex: 1,
    justifyContent: "center",
    alignItems: "flex-end",
  },
  container: {
    top: height * 0.15,
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  itemText: {
    fontSize: 18,
  },
  flexDirectionRow: {
    display: "flex",
    flexDirection: "row",
  },
  modifyAndDelete: {
    display: "flex",
    flexDirection: "row",
    top: "3%",
  },
  allAlert: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 10,
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#fff",
    borderRadius: 8,
    left: "4%",
    top: 5,
    marginBottom: 10,
    height: height * 0.2,
    width: width * 0.9,
  },
  actualPrice: {
    display: "flex",
    flexDirection: "row",
    top: height * 0.02,
  },
  targetPrice: {
    display: "flex",
    flexDirection: "row",
    top: height * 0.05,
  },
  input: {
    width: width * 0.55,
    height: height * 0.072,
    backgroundColor: "#F0F0F0",
    borderRadius: 10,
    borderColor: "#ff7c00",
    padding: 16,
    fontSize: 35,
    marginVertical: 10,
    left: width * 0.1,
    top: height * 0.01,
    color: "#436B92",
    textAlign: "center",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: "#F0F0F0",
    width: "80%",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 2,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: "#F194FF",
  },
  buttonClose: {
    backgroundColor: "#ff7b0d",
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  modalText: {
    color: "#666666",
    marginBottom: 15,
    right: "25%",
  },
  targetPriceOrAlert: {
    display: "flex",
    flexDirection: "row",
    top: height * 0.138,
    right: width * 0.53,
    width: width * 0.6,
    height: height * 0.05,
    borderWidth: 0.5,
    borderTopLeftRadius: 10,
    borderBottomRightRadius: 8,
    borderColor: "#B2B2B2",
    backgroundColor: "#F9F9F9",
    paddingVertical: 3,
  },
  flexDirectionColumn: {
    display: "flex",
    flexDirection: "column",
  },
  notificationLogo: {
    borderRadius: 50,
    borderWidth: 1,
    width: 40,
    height: 40,
    right: width * 0.33,
    top: height * 0.16,
  },
  mySelectionText: {
    fontSize: 20,
    fontFamily: "ManropeBold",
    textAlign: "center",
    bottom: height * 0.1,
  },
  modifyText: {
    left: width * 0.76,
    bottom: height * 0.09,
    fontSize: 16,
    color: "#436B92",
  },
  noneProductText: {
    fontFamily: "ManropeSemiBold",
    textAlign: "center",
    top: height * 0.25,
  },
  pressableAbort: {
    right: width * 0.3,
    bottom: height * 0.02,
  },
  abortText: {
    fontSize: 15,
    color: "#436B92",
  },
  modifyAlertPriceText: {
    fontSize: 18,
    right: "25%",
    right: width * 0.06,
    fontFamily: "ManropeBold",
  },
  activateAlertPriceTextModal: {
    fontSize: 20,
    fontFamily: "ManropeBold",
  },
  modalModifiyAlertView: {
    backgroundColor: "#fff",
    borderRadius: 10,
    top: height * 0.02,
    width: width * 0.75,
  },
  modalModifyAlertEuroSign: {
    fontSize: 35,
    color: "#436B92",
    left: width * 0.5,
    bottom: height * 0.065,
  },
  modalModifiyEconomizeText: {
    left: width * 0.35,
    bottom: height * 0.05,
    color: "#66666",
    fontFamily: "ManropeRegular",
  },
  modalModifiyPressableSave: {
    bottom: height * 0.26,
    left: width * 0.5,
  },
  modalModifiyAlertSaveText: {
    fontFamily: "ManropeBold",
    fontSize: 15,
    color: "#436B92",
  },
  activateEmailAlertView: {
    display: "flex",
    flexDirection: "row",
    bottom: height * 0.02,
  },
  receiveEmailAlertText: {
    color: "#262626",
    left: width * 0.05,
  },
  switchActiveEmail: {
    left: width * 0.1,
    bottom: height * 0.01,
  },
  deleteAlertButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#EA0000",
    backgroundColor: "#EA0000",
    width: width * 0.5,
    height: height * 0.05,
    bottom: height * 0.03,
    zIndex: 1,
  },
  deleteAlertText: {
    textAlign: "center",
    fontFamily: "ManropeSemiBold",
    color: "#fff",
    paddingVertical: 12,
  },
  selectItemToDeleteButton: {
    right: width * 0.15,
    top: height * 0.07,
    width: width * 0.08,
    height: height * 0.04,
  },
  imageItem: {
    width: width * 0.25,
    height: height * 0.12,
    right: width * 0.05,
  },
  itemInformationsView: {left: 15, top: 10, width: width * 0.5},
  itemTitle: {
    fontFamily: "ManropeSemiBold",
    fontSize: 17,
    width: "100%",
  },
  fromPriceText: {
    color: "grey",
    fontFamily: "ManropeRegular",
  },
  itemActualPrice: {
    color: "#262626",
    fontSize: 24,
    fontFamily: "ManropeBold",
    paddingLeft: 6,
    bottom: 10,
  },
  desiredPrice: {
    borderTopLeftRadius: 8,
    paddingLeft: 10,
    paddingVertical: 8,
    color: "#262626",
  },
  targetPrice: {
    paddingLeft: 5,
    fontFamily: "ManropeBold",
    color: "#262626",
    fontSize: 15,
    paddingVertical: 7,
  },
  notificationActiveView: {
    alignItems: "center",
    bottom: height * 0.1,
  },
  notificationsActiveLogo: {
    left: width * 0.012,
    top: height * 0.005,
  },
  activateAlertPriceText: {
    paddingLeft: 10,
    paddingVertical: 8,
    textAlign: "center",
  },
  inactiveNotificationsLogoView: {
    alignItems: "center",
    bottom: height * 0.1,
  },
  inactiveNotificationsLogo: {
    left: width * 0.012,
    top: height * 0.005,
  },
  trashButton: {
    left: width * 0.8,
    top: height * 0.65,
    width: width * 0.14,
    height: height * 0.06,
    borderWidth: 1,
    borderRadius: 100,
    borderColor: "#436B92",
    backgroundColor: "#436B92",
    position: "absolute",
  },
  trashLogo: {left: width * 0.03, top: height * 0.007},
  cptItemSelectedToDeleteView: {
    borderWidth: 1,
    borderRadius: 100,
    borderColor: "#436B92",
    backgroundColor: "#F0F0F0",
    bottom: height * 0.05,
    left: width * 0.1,
    width: width * 0.05,
  },
  cptItemSelectedToDeleteText: {
    fontFamily: "ManropeRegular",
    color: "#436B92",
    textAlign: "center",
  },
});
